### ISSUE TITLE
Edict not appearing

### ISSUE THREAD

**Issue by psytag** [AleksanderGondek/stellaris-mod-filthy-casual-mode#3]
I tried the mod but the edict is not appearing in game but it is downloaded. I tried other mods and the do work (i'm on 1.4 update)

**Comment by AleksanderGondek** [comment]
I will look into this soonTM, thanks for the report!

**Comment by AleksanderGondek** [comment]
Under version  1.4.1 (1759) with and without DLC: Leviathans Story Pack, the edict called “Blessing of Omnissaiah” is appearing on both of my PCs, when I start a new game. I have check before and after reinstallation of mod. 
Unfortunately, I have no way of checking if jump between version of games on save game is causing the behaviour.
What I can recommend: would you be so kind as to unsubscribe and subscribe again to the mod? This have fixed a few issues in the past.

**Comment by AleksanderGondek** [comment]
This was resolved. See [psytag comment](http://steamcommunity.com/sharedfiles/filedetails/?id=741819051).
