### ISSUE TITLE
Blessing of Omnissiah typo

### ISSUE THREAD

**Issue by drmike** [AleksanderGondek/stellaris-mod-filthy-casual-mode#4]
Greetings:

It's a minor thing but you have Sector Limit listed twice on the picture of Blessing of Omnissiah.

Thank you and thank for for continuing this mod.

**Comment by AleksanderGondek** [comment]
Greetings and salutations, friend!
Thanks for bug report - I will fix it _soonTM_.

**Comment by AleksanderGondek** [comment]
Fixed by 58a7f21ddf3fa66429e67bcd37d8e7decb287540
