### ISSUE TITLE
Stellaris 2.2 update and Blessing of Midas

### ISSUE THREAD

**Issue by Sora-Canstavia** [AleksanderGondek/stellaris-mod-filthy-casual-mode#5]
Hi there,

With the recent update of Stellaris to 2.2.1 the Blessing of Midas function in the mod broke. I Decided to have a poke around the mod files and got it somewhat working again, I Couldn't get it to affect the entire country, only the planets (tiles changed to jobs) and I Couldn't get it to affect Influence in any way, I Figured that if I Let you know that I'd done this, if you want I Can send the changed blessing of midas file to you, I Won't attach it right here because I Don't know how you'd feel about having it publicly visible here for everyone.

I Did find, by the way, that using "country_base_[resource]_produces_mult =" did allow the game to register the change for empire production, but didn't make any actual change. 

Also, my changes only take affect and are visible on the resource bar at the top on the first day of the in-game month, so setting it on the second day won't have any visible change until the first of the next month.

**Comment by AleksanderGondek** [comment]
Thank you a lot for taking time to investigate!
As it turns out, I also have been working on the very same thing and have just released it - please take a look and check, if there is something you did better, if so - let me know and we will incorporate it.

**Comment by Sora-Canstavia** [comment]
Ah! Thankyou for updating the mod! I Had a quick look at the new file and noticed you're using "country_base_[resource]_produces_add" I Assume the mult didn't work at all for that? 

For me, what I Got working was "planet_jobs_[resource]_produces_mult" the only resource that didn't work for was Influence, though. 
Just thought I'd let ya know on what I'd done incase you want to add that as well ^^ (the planet_jobs line replicates pretty much exactly what the tiles line did in the old version)
